### PR TITLE
Fixing circular import hell

### PR DESCRIPTION
**Pull request by LydiaFrance**
I was originally trying to run `download_era5` in the notebook as a function but found it wasn't being made available by the package. I tried to expose it and broke all the tests and created circular dependencies because of the `download_era5` module and the way it imports. #21 

To fix circular dependencies, added a `core.py` for everything that is shared across the different modules (config and logging). I've also reorganised the importing so there aren't clashes and it should be in a clear dependency hierarchy now. 

Key improvements:
- Common functionality (config parsing, logging) now imported by core.py, providing a single source of truth
- Clear Import Structure: Each module explicitly imports what it needs, making dependencies obvious
- Simplified Exports: Modules only export what other modules need, reducing coupling

### CODE REVIEW

**Review by dsj976 — APPROVED** [review]
Thanks @LydiaFrance, this looks good. I have simplified the import statements in the tests given these changes. At some point we should re-design the package architecture to get rid of the subfolders. See #23.

**Comment by dsj976** [comment]
@LydiaFrance please review my changes and approve if you are happy.

**Comment by LydiaFrance** [comment]
I can't review it because I'm the person who started the pull request, but it looks good to me. Thank you!

**Comment by dsj976** [comment]
@louisavz could you review and approve?

**Comment by dsj976** [comment]
Let's merge this one before #24

**Comment by dsj976** [comment]
@louisavz would be great to get your approval on this so that we can merge.
@ots22 if you are not too busy, would be great if you could also give your opinion. I think there is still a bit we can do to better handle imports (see #23 for example).

**Review by ots22 — APPROVED** [review]
This is a better structure to the imports, looks good to me.

Agree it would be good to address #23 as well, either in this PR or another one.

**Comment by louisavz** [comment]
So sorry @dsj976, just saw your message, looks like it's merged successfully. Apologies for the delay.

**Pull request merged**
